spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: server
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}?currentSchema=public
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate

auth:
  issuer: delvex
  access-token-secret: ${ACCESS_TOKEN_SECRET}
  access-token-ttl: 15m
